In [34]:
import pykitti
import numpy as np
import open3d as o3d
import matplotlib.pyplot as plt

In [35]:
basedir = '/media/cyj/DATA/hybrid_feature_LO/datasets'
date = '2011_10_03'
drive = '0027'
dataset = pykitti.raw(basedir, date, drive)


# ICP配准

In [36]:
import numpy as np
from sklearn.neighbors import NearestNeighbors


def best_fit_transform(A, B):
    '''
    Calculates the least-squares best-fit transform that maps corresponding points A to B in m spatial dimensions
    Input:
      A: Nxm numpy array of corresponding points
      B: Nxm numpy array of corresponding points
    Returns:
      T: (m+1)x(m+1) homogeneous transformation matrix that maps A on to B
      R: mxm rotation matrix
      t: mx1 translation vector
    '''

    assert A.shape == B.shape

    # get number of dimensions
    m = A.shape[1]

    # translate points to their centroids
    centroid_A = np.mean(A, axis=0)
    centroid_B = np.mean(B, axis=0)
    AA = A - centroid_A
    BB = B - centroid_B

    # rotation matrix
    H = np.dot(AA.T, BB)
    U, S, Vt = np.linalg.svd(H)
    R = np.dot(Vt.T, U.T)

    # special reflection case
    if np.linalg.det(R) < 0:
       Vt[m-1,:] *= -1
       R = np.dot(Vt.T, U.T)

    # translation
    t = centroid_B.T - np.dot(R,centroid_A.T)

    # homogeneous transformation
    T = np.identity(m+1)
    T[:m, :m] = R
    T[:m, m] = t

    return T, R, t


def nearest_neighbor(src, dst):
    '''
    Find the nearest (Euclidean) neighbor in dst for each point in src
    Input:
        src: Nxm array of points
        dst: Nxm array of points
    Output:
        distances: Euclidean distances of the nearest neighbor
        indices: dst indices of the nearest neighbor
    '''

    assert src.shape == dst.shape

    neigh = NearestNeighbors(n_neighbors=1)
    neigh.fit(dst)
    distances, indices = neigh.kneighbors(src, return_distance=True)
    return distances.ravel(), indices.ravel()


def icp(A, B, init_pose=None, max_iterations=20, tolerance=0.001):
    '''
    The Iterative Closest Point method: finds best-fit transform that maps points A on to points B
    Input:
        A: Nxm numpy array of source mD points
        B: Nxm numpy array of destination mD point
        init_pose: (m+1)x(m+1) homogeneous transformation
        max_iterations: exit algorithm after max_iterations
        tolerance: convergence criteria
    Output:
        T: final homogeneous transformation that maps A on to B
        distances: Euclidean distances (errors) of the nearest neighbor
        i: number of iterations to converge
    '''

    assert A.shape == B.shape

    # get number of dimensions
    m = A.shape[1]

    # make points homogeneous, copy them to maintain the originals
    src = np.ones((m+1,A.shape[0]))
    dst = np.ones((m+1,B.shape[0]))
    src[:m,:] = np.copy(A.T)
    dst[:m,:] = np.copy(B.T)

    # apply the initial pose estimation
    if init_pose is not None:
        src = np.dot(init_pose, src)

    prev_error = 0

    for i in range(max_iterations):
        # find the nearest neighbors between the current source and destination points
        distances, indices = nearest_neighbor(src[:m,:].T, dst[:m,:].T)

        # compute the transformation between the current source and nearest destination points
        T,_,_ = best_fit_transform(src[:m,:].T, dst[:m,indices].T)

        # update the current source
        src = np.dot(T, src)

        # check error
        mean_error = np.mean(distances)
        if np.abs(prev_error - mean_error) < tolerance:
            break
        prev_error = mean_error

    # calculate final transformation
    T,_,_ = best_fit_transform(A, src[:m,:].T)

    return T, distances, i

In [62]:
def equalize_point_clouds(A, B):
    """
    Equalize the number of points in two point clouds by randomly downsampling the larger one.
    """
    if A.shape[0] > B.shape[0]:
        # 如果A的点数多于B，随机下采样A
        indices = np.random.choice(A.shape[0], B.shape[0], replace=False)
        return A[indices], B
    elif A.shape[0] < B.shape[0]:
        # 如果B的点数多于A，随机下采样B
        indices = np.random.choice(B.shape[0], A.shape[0], replace=False)
        return A, B[indices]
    else:
        # 如果点数相等，直接返回
        return A, B

data1_equalized, data2_equalized = equalize_point_clouds(data1, data2)
print('data1_equalized.shape', data1_equalized.shape)
print('data2_equalized.shape', data2_equalized.shape)

data1_equalized.shape (124134, 3)
data2_equalized.shape (124134, 3)


In [61]:
#取两帧的点云
data1 = dataset.get_velo(25)
data2 = dataset.get_velo(30)
point_cloud1 = o3d.geometry.PointCloud()
data1 = data1[:, :3]
point_cloud1.points = o3d.utility.Vector3dVector(data1)
point_cloud2 = o3d.geometry.PointCloud()
data2 = data2[:, :3]
point_cloud2.points = o3d.utility.Vector3dVector(data2)

In [63]:
T, distances, i = icp(data2_equalized, data1_equalized)
print('T', T)
print('distances', distances)
print('distances.shape',distances.shape)
print('i', i)

T [[ 0.99994599  0.00640007  0.00818915  0.22829941]
 [-0.00633409  0.99994748 -0.00805761 -0.09008628]
 [-0.00824029  0.00800531  0.999934   -0.18372211]
 [ 0.          0.          0.          1.        ]]
distances [0.82871525 1.31756822 2.20333232 ... 0.19908368 0.17243294 0.22725444]
distances.shape (124134,)
i 4


In [64]:
import copy
# o3d可视化点云配准结果
def draw_registration_result(source, target, transformation):
    source_temp = copy.deepcopy(source)
    target_temp = copy.deepcopy(target)
    source_temp.paint_uniform_color([1, 0.706, 0])
    target_temp.paint_uniform_color([0, 0.651, 0.929])
    source_temp.transform(transformation)
    o3d.visualization.draw_geometries([source_temp, target_temp],
                                      zoom=0.4459,
                                      front=[0.9288, -0.2951, -0.2242],
                                      lookat=[1.6784, 2.0612, 1.4451],
                                      up=[-0.3402, -0.9189, -0.1996])

In [67]:
print(T)
#变换矩阵
draw_registration_result(point_cloud2, point_cloud1, T)

[[ 0.99994599  0.00640007  0.00818915  0.22829941]
 [-0.00633409  0.99994748 -0.00805761 -0.09008628]
 [-0.00824029  0.00800531  0.999934   -0.18372211]
 [ 0.          0.          0.          1.        ]]
